services:
  frontend:
    image: nginx:latest
    container_name: web-project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    ports:
      - "80:80"