services:
  frontend:
    image: nginx:latest
    container_name: web-project
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .:/usr/share/nginx/html
    ports:
      - "8081:80"         # Expose le port 80 du conteneur sur le port 8081 de l'hôte
    networks:
      - chess-network

  backend-chess:
    build:
      context: ./backend/chess
      dockerfile: Dockerfile
    container_name: chess-api
    ports:
      - "8082:8080"       # Expose le port 8080 du conteneur sur le port 8082 de l'hôte
    volumes:
      - ./backend/chess:/appChess  # Assurez-vous que le WORKDIR (ci-dessous) est identique (ici, "/app")
    networks:
      - chess-network

networks:
  chess-network:
    driver: bridge
